- name: Backend App
  hosts: backend
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Disable default NodeJS Version Module
      ansible.builtin.shell: dnf module disable nodejs -y
    
    - name: Enable NodeJS module for V20
      ansible.builtin.shell: dnf module enable nodejs:20 -y
  
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Install unzip and tar
      ansible.builtin.dnf:
        name: 
          - unzip
          - tar
          - gzip 
          - bzip2
        state: present      

    - name: Adding Application User
      ansible.builtin.user:
        name: expense
    
    - name: Clean the old Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and Extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes 

    - name: Download NodeJS Dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /app
      
    - name: Copy Backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: installed  

    - name: Install pip for Python 3.9
      ansible.builtin.command:
        cmd: python3.9 -m ensurepip --upgrade
  
    - name: Install Python MySQL Client
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: /usr/local/bin/pip3.9      

    - name: Load Schema
      ansible.builtin.shell:
        cmd: mysql -u root -p 'ExpenseApp@1' -h 172.31.20.108 < /app/schema/backend.sql
        #state: import 
        #name: all
        #target: /app/schema/backend.sql
        #login_user: root
        #login_password: ExpenseApp@1
        #login_host: 172.31.20.108

    - name: Start Backend Service
      ansible.builtin.systemd_service:
        name: backend
        state: restarted   
        enabled: yes
        daemon_reload: yes         



