- name: Mysql Setup
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started    
        enabled: yes   

    - name: Set MySQL password
      community.mysql.mysql_user:
        name: root
        host: 172.31.20.108
        password: ExpenseApp@1
        login_unix_socket: /var/lib/mysql/mysql.sock
      no_log: true
    #- name: Setup MySQL Password
    #  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1       